### ISSUE TITLE
'any' encofing fails

### ISSUE THREAD

**Issue by jeremiehuchet** [h2non/jshashes#29]
I'm executing: 

```
new Hashes.SHA256().any('test', "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789`~!@#$%^&*()_-+={}|[]\\:\";'<>?,./")
```

which give me `A-*A_[Hza*ek.e]hlq*%VwLgH0zDi-?4);_0tbQk`,
but I'm expecting something like `-*A_[Hza*ek.e]hlq*%VwLgH0zDi-?4);_0tbQk\`, without the `A` prefix.

I'm not sure I'm expecting the right result, but I observed a lot of outputs beginning with the first character of my _encoding_ (A).

Using SHA1, the result seems to be OK, but I'm suspecting the same issue appears with MD5 and SHA512.

**Comment by kops** [comment]
I made some additional tests, I think the issue depends on the amount of characters set in the _encoding_.

SHA256 using an _encoding_ of 82 characters:
    new Hashes.SHA256().any('test', 'Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa')

results in `AaaaaaaaaaaaaAaaaaaaaaaaaaaaaaaaaaaaaaaaa`
but I'm expecting `aaaaaaaaaaaaAaaaaaaaaaaaaaaaaaaaaaaaaaaaa`

**Comment by Ruffio** [comment]
@jeremiehuchet has this issue been fixed and can therefore be closed?

**Comment by Ruffio** [comment]
@h2non IMHO this issue should be closed as it has been fixed long time ago...

**Comment by jeremiehuchet** [comment]
You are right,
I am sorry I didn't replied. I thought I can find some time to attempt to reproduce the issue or confirm it is solved.
