### ISSUE TITLE
PhantomJS

### ISSUE THREAD

**Issue by tomastrajan** [h2non/jshashes#32]
It seems so that it doesn't work in PhantomJS, it always returns the same hash for different outpusts (tested with MD5 and SHA1), works as expected in Chrome and Firefox

**Comment by h2non** [comment]
Thanks for reporting. Will dig into it.

**Comment by tomastrajan** [comment]
I actually found the problem, it's Phantom JS issue, i was passing the "arguments" object into hash function and in phantom it was unfortunately empty. It can be solved by calling Array.prototype.slice.call(arguments), which return array of arguments with real values.
