### ISSUE TITLE
SHA-384 support

### ISSUE THREAD

**Issue by asauber** [h2non/jshashes#33]
Hi, I'm working on a project that I'd like to support SHA-384. Any plans to implement this?

**Comment by h2non** [comment]
There's no plan for that, however if you can provide a good implementation, I'm open to merge it.

**Comment by Ruffio** [comment]
According to Wiki, the SHA-384 is just a truncated version of 512: https://en.wikipedia.org/wiki/Secure_Hash_Algorithms

**Comment by Ruffio** [comment]
@h2non this issue should be closed as no implementation has been provided within a year...

**Comment by h2non** [comment]
Right, I don't even think I would support that either. Closing...
