### ISSUE TITLE
b64 padding .... bug/typpo ?

### ISSUE THREAD

**Issue by develmts** [h2non/jshashes#34]
Digging on code,  I found that.. and it seems strange
`b64pad = (options && typeof options.pad === 'string') ? options.pda : '=', // base-64 pad character. Defaults to '=' for strict RFC compliance`

Shouldn't  **options.pda**   be   **options.pad** ?

If that's the case, i suspect same bug/typpo will repeat fro other Hash classes

**Comment by h2non** [comment]
Yeah, looks like it's a typo. Will fix asap.

**Comment by h2non** [comment]
Fixed in `v1.0.6`. Thanks for reporting.
