### ISSUE TITLE
On Yarn, "warning jshashes@1.0.6: The engine "browser" appears to be invalid."

### ISSUE THREAD

**Issue by xml** [h2non/jshashes#35]
`warning jshashes@1.0.6: The engine "browser" appears to be invalid.`

This appears when using various versions of Yarn (rather than npm) to install jshashes, either individually or in combination. 

It happens in all environments, both in my local and in CI builds. 

When googling the error string, it appears to be happening in many other builds as well. 

It's *non-blocking*. But, FYI.

**Comment by h2non** [comment]
Fixed in master.

**Comment by Ruffio** [comment]
@xml has this issue been resolved? If yes, please close this issue.

**Comment by Ruffio** [comment]
@h2non if this issue has been fixed, shouldn't this issue be closed?

**Comment by h2non** [comment]
Yeah, this was fixed in `v1.0.7`.
