### ISSUE TITLE
 Hashes.Base64.decode  parse errors

### ISSUE THREAD

**Issue by xiaoxiao95888** [h2non/jshashes#36]
Hashes.Base64.decode  parse errors

 b64.decode(b64.encode(str))

**Comment by Ruffio** [comment]
@xiaoxiao95888 can you provide an example of 'string' that produces a wrong output after encoding and decoding?

**Comment by Ruffio** [comment]
@h2non this issue should be closed du to lack of response from originator...

**Comment by h2non** [comment]
I'm fine with that. Thanks!
