### ISSUE TITLE
jsDelivr CDN file set

### ISSUE THREAD

**Issue by yzITI** [h2non/jshashes#42]
[This package](https://www.jsdelivr.com/package/npm/jshashes) doesn't have a [default file](https://www.jsdelivr.com/features#publishing-packages) set. You can set it via `jsdelivr`, `browser`, or `main` field in `package.json`

which will make it more convenient! : )

**Comment by h2non** [comment]
Fixed in `v1.0.8`:
https://cdn.jsdelivr.net/npm/jshashes@1.0.8

Thanks for the heads up!
