### ISSUE TITLE
TypeScript type declaration file

### ISSUE THREAD

**Issue by geopic** [h2non/jshashes#45]
If you want I can write a TypeScript type declaration file for this package so that TS developers can utilise the type-checking feature of the language as they use this package. Let me know if you are interested.

**Comment by h2non** [comment]
I'm happy to onboard a TS interface definitions file. Feel free to create a PR.

**Comment by toby5box** [comment]
@geopic Can you share how you're importing this library into TS right now? I've never found the SO answers about this very helpful and I would like to use this library in a TS project today. TIA

**Comment by geopic** [comment]
@h2non Good stuff, I'll start on it soon.

@toby5box Can you clarify how familiar you are with TS? What is your development environment like? Using this library as an npm package is the same as every other npm package. At the moment it has no types definition file so using the library in a `.ts` file would not provide type hinting.

**Comment by bno1** [comment]
This was fixed in May but it's not yet released on npm.

**Comment by allidoisace** [comment]
Still isn't released. What the heck. It's been 2 years.
